[manager]

# https://github.com/sxyazi/yazi/blob/0ebfacb677aeb32ba749c738493993af997c0485/yazi-config/preset/keymap.toml#L4
prepend_keymap = [
  { on = [
    "q",
  ], run = "quit", desc = "Exit the process" },

  { on = [
    "k",
  ], run = "arrow -1", desc = "Move cursor up" },
  { on = [
    "j",
  ], run = "arrow 1", desc = "Move cursor down" },

  { on = [
    "h",
  ], run = "leave", desc = "Go back to the parent directory" },

  # { on = [
  #   "l",
  # ], run = "enter", desc = "Enter the child directory" },

  # https://github.com/p-kolacz/dotfiles/blob/f8309a42ab07eaecb210e9608f88b334a655419d/.config/yazi/keymap.toml#L6
  { on = [
    "l",
  ], run = "plugin --sync smart-enter", desc = "Enter the child directory, or open the file" },

  { on = [
    "E",
  ], run = "shell /usr/bin/bash --block --confirm" },

  { on = [
    "o",
  ], run = "open", desc = "Open the selected files" },

  { on = [
    "g",
    "l",
  ], run = "cd ~/.local/", desc = "Goto .local" },
]
