"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

# https://github.com/p-kolacz/dotfiles/blob/f8309a42ab07eaecb210e9608f88b334a655419d/.config/yazi/keymap.toml#L6
# https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/keymap-default.toml

[manager]
prepend_keymap = [

  # { on = "o", run = "open" },
  { on = "<C-f>", run = "plugin fzf" },
  { on = "E", run = "shell /usr/bin/bash --block --confirm" },
  { on = "F", run = "filter --smart" },
  { on = "G", run = "arrow 99999999" },
  { on = "H", run = "tab_switch -1 --relative" },
  { on = "J", run = "arrow 50%" },
  { on = "K", run = "arrow -50%" },
  { on = "L", run = "tab_switch 1 --relative" },
  { on = "T", run = "tab_create --current" },                   # C-t conflicts with wezterm
  { on = "h", run = "leave" },
  { on = "j", run = "arrow 1" },
  { on = "k", run = "arrow -1" },                               # TODO: wrap
  { on = "l", run = "plugin smart-enter" },
  { on = "q", run = "close" },
  { on = "s", run = "sort alphabetical --reverse=no" },
  { on = "w", run = "tasks_show", desc = "Show task manager" },

  { on = [ "d", "c" ], run = "plugin what-size", desc = "Calc size of selection or cwd" },                              # this is not the ux i want, but i'll accept it for now
  { on = [ "d", "d" ], run = "yank --cut", desc = "Cut the selected files" },
  { on = [ "g", "g" ], run = "arrow -99999999", desc = "Move cursor to the top" },
  { on = [ "o", "C" ], run = [ "sort mtime --reverse=no", "linemode mtime" ], desc = "Sort by created time" },
  { on = [ "o", "c" ], run = [ "sort mtime --reverse", "linemode mtime" ], desc = "Sort by created time (reverse)" },
  { on = [ "p", "L" ], run = "hardlink", desc = "Hardlink the files" },
  { on = [ "p", "l" ], run = "link", desc = "Symlink the files" },
  { on = [ "p", "p" ], run = "paste", desc = "Paste the files" },
  { on = [ "y", "n" ], run = "copy filename", desc = "Copy the filename" },
  { on = [ "y", "p" ], run = "copy path", desc = "Copy the file path" },
  { on = [ "y", "y" ], run = "yank --cut", desc = "Copy the selected files" },
  { on = [ "z", "h" ], run = "hidden toggle", desc = "Toggle the visibility of hidden files" },

  { on = [ "0" ], run = "plugin relative-motions --args=0", desc = "Move in relative steps" },
  { on = [ "1" ], run = "plugin relative-motions --args=1", desc = "Move in relative steps" },
  { on = [ "2" ], run = "plugin relative-motions --args=2", desc = "Move in relative steps" },
  { on = [ "3" ], run = "plugin relative-motions --args=3", desc = "Move in relative steps" },
  { on = [ "4" ], run = "plugin relative-motions --args=4", desc = "Move in relative steps" },
  { on = [ "5" ], run = "plugin relative-motions --args=5", desc = "Move in relative steps" },
  { on = [ "6" ], run = "plugin relative-motions --args=6", desc = "Move in relative steps" },
  { on = [ "7" ], run = "plugin relative-motions --args=7", desc = "Move in relative steps" },
  { on = [ "8" ], run = "plugin relative-motions --args=8", desc = "Move in relative steps" },
  { on = [ "9" ], run = "plugin relative-motions --args=9", desc = "Move in relative steps" },

]
