# https://wiki.archlinux.org/title/XDG_Desktop_Portal
# https://github.com/search?type=code&q=filechooser+path%3A**%2Fxdg-desktop-portal%2Fportals.conf
# this file is loaded on application startup
# important for ff 149: https://bbs.archlinux.org/viewtopic.php?pid=2292357#p2292357
[preferred]
default=gtk
# gtk file chooser seems to be broken
org.freedesktop.impl.portal.FileChooser=lxqt
